Lang.prototype.pack.xh = {
	"token": {
		"HOME":"IKHASI LASEKHAYA",
		"CAMPAIGNS":"AMAPHULO",
		"SURVEYS":"UVAVANYO-MIBUZO",
		"TOPICS":"UMXHOLO",
		"NEWS":"IINDABA",
		"SERVICES":"IINKONZO ZEMPILO",
		"EVENTS":"IMICIMBI",
		"Profile":"Iprofayile",
		"Change Password":"Tshinstha iPhaswedi",
		"Logout":"Phuma",
		"Switch to isiXhosa":"Ukutshintsha ulwimiusuka kwiSingesi"
	},	
	"regex": [
		["home", "i", "ikhasi lasekhaya"],
		["campaigns", "i", "amaphulo"],
		["surveys", "i", "Uvavanyo-mibuzo"],
		["topics", "i", "umxholo"],
		["news", "i", "nkhani"],
		["services", "i", "ntchito"],
		["events", "i", "imicimbi"]
	]
};