Lang.prototype.pack.xh = {
	"token": {
		"HOME":"PAKHOMO",
		"CAMPAIGNS":"KAMPENI",
		"SURVEYS":"KAPFUKUPFUKU",
		"TOPICS":"MITU",
		"NEWS":"NKHANI",
		"SERVICES":"NTCHITO",
		"EVENTS":"ZOCHITIKA",
		"Profile":"Za Ine",
		"Change Password":"Sintha password",
		"Logout":"Tuluka"
	},	
	"regex": [
		["home", "i", "pakhomo"],
		["campaigns", "i", "kampeni"],
		["surveys", "i", "kafukufuku"],
		["topics", "i", "mitu"],
		["news", "i", "nkhani"],
		["services", "i", "ntchito"],
		["events", "i", "zochitika"]
	]
};